# 1. Utilisation de l'image 3.11 de Python version slim
FROM python:3.11-slim

# 2. Création d'un dossier pour les scripts
WORKDIR /Scripts

# 3. Installation de la librairie pandas
RUN pip install --no-cache-dir pandas requests

# 4. Ouverture d'une console
CMD ["bash"]